import breakpoints from './breakpoints';

const typography = {
  fontFamily: 'Arial',
  fontSize: 13,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  h1: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '125%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1.5rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '1.25rem' },
  },
  h2: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '125%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1.25rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '1.125rem' },
  },
  h3: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '125%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1.125rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '1rem' },
  },
  h4: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '125%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '0.875rem' },
  },
  body1: { 
    fontFeatureSettings: '\'liga\' off, \'clig\' off', 
    fontSize: '1rem', 
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '150%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '1rem' },
  },
  body2: { 
    fontFeatureSettings: '\'liga\' off, \'clig\' off', 
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '143%',
    letterSpacing: '0.17px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '0.875rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '0.875rem' },
  },
  subtitle1: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '175%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '1rem' },
  },
  subtitle2: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '157%',
    letterSpacing: '0.1px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '0.875rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '0.875rem' },
  },
  overline: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '266%',
    letterSpacing: '0.1px',
    textTransform: 'uppercase',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '0.75rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '0.75rem' },
  },
  caption: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '166%',
    letterSpacing: '0.4px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '0.75rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '0.75rem' },
  },
  dataLabel: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '100%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '0.875rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '0.875rem' },
  },
  dataValue: {
    fontFeatureSettings: '\'liga\' off, \'clig\' off',
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '125%',
    letterSpacing: '0.15px',
    [`@media (max-width: ${breakpoints.values.md}px)`]: { fontSize: '1rem' },
    [`@media (max-width: ${breakpoints.values.sm}px)`]: { fontSize: '1rem' },
  },
  button: { 
    fontFeatureSettings: '\'liga\' off, \'clig\' off', 
    small: {
      textTransform: 'uppercase',
      fontStyle: 'normal',
      fontWeight: 500,
      fontSize: '0.8125rem',
      lineHeight: '1.375rem',
      letterSpacing: '0.46px',
    },
    medium: {
      textTransform: 'uppercase',
      fontStyle: 'normal',
      fontWeight: 500,
      fontSize: '0.875rem',
      lineHeight: '1.5rem',
      letterSpacing: '0.4px',
    },
  },
};

export default typography;
